apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-envoy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: fake
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: helmtest
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2

