apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: envoytest-kustom
  namespace: flux-system
spec:
  interval: 15m
  path: "./envoy/templates"
  prune: true
  sourceRef:
    kind: GitRepository
    name: helmtest
